/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1med (void);
GtkWidget* create_window2med (void);
GtkWidget* create_window3med (void);
GtkWidget* create_window4med (void);
GtkWidget* create_window5med (void);
GtkWidget* create_window6med (void);
GtkWidget* create_window7med (void);
GtkWidget* create_window8med (void);
