/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1med (void)
{
  GtkWidget *window1med;
  GtkWidget *fixed1;
  GtkWidget *entry1med;
  GtkWidget *entry2med;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *button2;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image25;
  GtkWidget *label62;
  GtkWidget *button1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label4;
  GtkWidget *image24;

  window1med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1med), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1med), fixed1);

  entry1med = gtk_entry_new ();
  gtk_widget_show (entry1med);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1med, 144, 64);
  gtk_widget_set_size_request (entry1med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1med), 8226);

  entry2med = gtk_entry_new ();
  gtk_widget_show (entry2med);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2med, 144, 112);
  gtk_widget_set_size_request (entry2med, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2med), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2med), 8226);

  label2 = gtk_label_new (_("password"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 48, 112);
  gtk_widget_set_size_request (label2, 72, 24);

  label1 = gtk_label_new (_("username"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 56, 64);
  gtk_widget_set_size_request (label1, 72, 24);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 432, 288);
  gtk_widget_set_size_request (button2, 96, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button2), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image25 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox24), image25, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("close"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox24), label62, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 24, 288);
  gtk_widget_set_size_request (button1, 96, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("login"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  image24 = create_pixmap (window1med, "chayma.png");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed1), image24, 8, 0);
  gtk_widget_set_size_request (image24, 528, 392);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1med, window1med, "window1med");
  GLADE_HOOKUP_OBJECT (window1med, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1med, entry1med, "entry1med");
  GLADE_HOOKUP_OBJECT (window1med, entry2med, "entry2med");
  GLADE_HOOKUP_OBJECT (window1med, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1med, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1med, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1med, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window1med, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window1med, image25, "image25");
  GLADE_HOOKUP_OBJECT (window1med, label62, "label62");
  GLADE_HOOKUP_OBJECT (window1med, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1med, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1med, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1med, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1med, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1med, image24, "image24");

  return window1med;
}

GtkWidget*
create_window2med (void)
{
  GtkWidget *window2med;
  GtkWidget *fixed2;
  GtkWidget *image33;
  GtkWidget *label5med;
  GtkWidget *button4;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label39;
  GtkWidget *button26;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image26;
  GtkWidget *label69;
  GtkWidget *button17;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label44;
  GtkWidget *button28;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image35;
  GtkWidget *label76;

  window2med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2med), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2med), fixed2);

  image33 = create_pixmap (window2med, "chayma2.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed2), image33, 24, 8);
  gtk_widget_set_size_request (image33, 488, 120);

  label5med = gtk_label_new (_("Bienvenue dans l'espace nutritioniste"));
  gtk_widget_show (label5med);
  gtk_fixed_put (GTK_FIXED (fixed2), label5med, 144, 136);
  gtk_widget_set_size_request (label5med, 264, 40);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 152, 248);
  gtk_widget_set_size_request (button4, 256, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button4), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Fiches patients"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox10), label39, FALSE, FALSE, 0);

  button26 = gtk_button_new ();
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed2), button26, 152, 184);
  gtk_widget_set_size_request (button26, 248, 40);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button26), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image26 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox25), image26, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Mon profil"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox25), label69, FALSE, FALSE, 0);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed2), button17, 152, 312);
  gtk_widget_set_size_request (button17, 256, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button17), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Disponibilit\303\251"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox15), label44, FALSE, FALSE, 0);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed2), button28, 256, 376);
  gtk_widget_set_size_request (button28, 88, 32);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (button28), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image35 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox32), image35, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("logout"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox32), label76, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26, "clicked",
                    G_CALLBACK (on_button26_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button28, "clicked",
                    G_CALLBACK (on_button28_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2med, window2med, "window2med");
  GLADE_HOOKUP_OBJECT (window2med, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2med, image33, "image33");
  GLADE_HOOKUP_OBJECT (window2med, label5med, "label5med");
  GLADE_HOOKUP_OBJECT (window2med, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2med, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window2med, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window2med, image10, "image10");
  GLADE_HOOKUP_OBJECT (window2med, label39, "label39");
  GLADE_HOOKUP_OBJECT (window2med, button26, "button26");
  GLADE_HOOKUP_OBJECT (window2med, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window2med, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window2med, image26, "image26");
  GLADE_HOOKUP_OBJECT (window2med, label69, "label69");
  GLADE_HOOKUP_OBJECT (window2med, button17, "button17");
  GLADE_HOOKUP_OBJECT (window2med, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window2med, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window2med, image15, "image15");
  GLADE_HOOKUP_OBJECT (window2med, label44, "label44");
  GLADE_HOOKUP_OBJECT (window2med, button28, "button28");
  GLADE_HOOKUP_OBJECT (window2med, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window2med, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (window2med, image35, "image35");
  GLADE_HOOKUP_OBJECT (window2med, label76, "label76");

  return window2med;
}

GtkWidget*
create_window3med (void)
{
  GtkWidget *window3med;
  GtkWidget *fixed3;
  GtkWidget *treeview1med;
  GtkWidget *entry8med;
  GtkWidget *entry9med;
  GtkWidget *label6;
  GtkWidget *button8;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label41;
  GtkWidget *button9;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label42;
  GtkWidget *button10;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label43;
  GtkWidget *button7;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image28;
  GtkWidget *label70;
  GtkWidget *label22med;
  GtkWidget *label21med;

  window3med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3med), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3med), fixed3);

  treeview1med = gtk_tree_view_new ();
  gtk_widget_show (treeview1med);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1med, 144, 56);
  gtk_widget_set_size_request (treeview1med, 456, 224);

  entry8med = gtk_entry_new ();
  gtk_widget_show (entry8med);
  gtk_fixed_put (GTK_FIXED (fixed3), entry8med, 384, 408);
  gtk_widget_set_size_request (entry8med, 80, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8med), 8226);

  entry9med = gtk_entry_new ();
  gtk_widget_show (entry9med);
  gtk_fixed_put (GTK_FIXED (fixed3), entry9med, 536, 408);
  gtk_widget_set_size_request (entry9med, 88, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9med), 8226);

  label6 = gtk_label_new (_("MY GYM"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 368, 16);
  gtk_widget_set_size_request (label6, 80, 24);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 208, 352);
  gtk_widget_set_size_request (button8, 88, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button8), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox12), label41, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed3), button9, 376, 360);
  gtk_widget_set_size_request (button9, 88, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button9), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox13), label42, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed3), button10, 520, 360);
  gtk_widget_set_size_request (button10, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button10), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox14), label43, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 592, 0);
  gtk_widget_set_size_request (button7, 80, 32);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button7), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image28 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox26), image28, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox26), label70, FALSE, FALSE, 0);

  label22med = gtk_label_new (_("CIN"));
  gtk_widget_show (label22med);
  gtk_fixed_put (GTK_FIXED (fixed3), label22med, 480, 408);
  gtk_widget_set_size_request (label22med, 49, 17);

  label21med = gtk_label_new (_("CIN"));
  gtk_widget_show (label21med);
  gtk_fixed_put (GTK_FIXED (fixed3), label21med, 328, 408);
  gtk_widget_set_size_request (label21med, 49, 17);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3med, window3med, "window3med");
  GLADE_HOOKUP_OBJECT (window3med, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3med, treeview1med, "treeview1med");
  GLADE_HOOKUP_OBJECT (window3med, entry8med, "entry8med");
  GLADE_HOOKUP_OBJECT (window3med, entry9med, "entry9med");
  GLADE_HOOKUP_OBJECT (window3med, label6, "label6");
  GLADE_HOOKUP_OBJECT (window3med, button8, "button8");
  GLADE_HOOKUP_OBJECT (window3med, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window3med, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window3med, image12, "image12");
  GLADE_HOOKUP_OBJECT (window3med, label41, "label41");
  GLADE_HOOKUP_OBJECT (window3med, button9, "button9");
  GLADE_HOOKUP_OBJECT (window3med, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window3med, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window3med, image13, "image13");
  GLADE_HOOKUP_OBJECT (window3med, label42, "label42");
  GLADE_HOOKUP_OBJECT (window3med, button10, "button10");
  GLADE_HOOKUP_OBJECT (window3med, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window3med, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window3med, image14, "image14");
  GLADE_HOOKUP_OBJECT (window3med, label43, "label43");
  GLADE_HOOKUP_OBJECT (window3med, button7, "button7");
  GLADE_HOOKUP_OBJECT (window3med, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window3med, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window3med, image28, "image28");
  GLADE_HOOKUP_OBJECT (window3med, label70, "label70");
  GLADE_HOOKUP_OBJECT (window3med, label22med, "label22med");
  GLADE_HOOKUP_OBJECT (window3med, label21med, "label21med");

  return window3med;
}

GtkWidget*
create_window4med (void)
{
  GtkWidget *window4med;
  GtkWidget *fixed4;
  GtkWidget *entry3med;
  GtkWidget *entry4med;
  GtkObject *spinbutton1med_adj;
  GtkWidget *spinbutton1med;
  GtkObject *spinbutton2med_adj;
  GtkWidget *spinbutton2med;
  GtkObject *spinbutton3med_adj;
  GtkWidget *spinbutton3med;
  GtkWidget *entry5med;
  GtkWidget *entry6med;
  GtkWidget *entry7med;
  GtkWidget *entry15med;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *button11;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label14;
  GtkWidget *button14;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image29;
  GtkWidget *label71;
  GtkWidget *label34med;
  GtkWidget *label8med;
  GtkWidget *label9med;
  GtkWidget *label17med;
  GtkWidget *label18med;
  GtkWidget *label19med;
  GtkWidget *label10;

  window4med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4med), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4med), fixed4);

  entry3med = gtk_entry_new ();
  gtk_widget_show (entry3med);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3med, 128, 56);
  gtk_widget_set_size_request (entry3med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3med), 8226);

  entry4med = gtk_entry_new ();
  gtk_widget_show (entry4med);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4med, 128, 96);
  gtk_widget_set_size_request (entry4med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4med), 8226);

  spinbutton1med_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1med_adj), 1, 0);
  gtk_widget_show (spinbutton1med);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1med, 168, 136);
  gtk_widget_set_size_request (spinbutton1med, 60, 27);

  spinbutton2med_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2med_adj), 1, 0);
  gtk_widget_show (spinbutton2med);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2med, 296, 136);
  gtk_widget_set_size_request (spinbutton2med, 48, 24);

  spinbutton3med_adj = gtk_adjustment_new (1, 1900, 2013, 1, 10, 10);
  spinbutton3med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3med_adj), 1, 0);
  gtk_widget_show (spinbutton3med);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3med, 400, 136);
  gtk_widget_set_size_request (spinbutton3med, 56, 24);

  entry5med = gtk_entry_new ();
  gtk_widget_show (entry5med);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5med, 128, 184);
  gtk_widget_set_size_request (entry5med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5med), 8226);

  entry6med = gtk_entry_new ();
  gtk_widget_show (entry6med);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6med, 128, 224);
  gtk_widget_set_size_request (entry6med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6med), 8226);

  entry7med = gtk_entry_new ();
  gtk_widget_show (entry7med);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7med, 128, 264);
  gtk_widget_set_size_request (entry7med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7med), 8226);

  entry15med = gtk_entry_new ();
  gtk_widget_show (entry15med);
  gtk_fixed_put (GTK_FIXED (fixed4), entry15med, 128, 16);
  gtk_widget_set_size_request (entry15med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15med), 8226);

  label13 = gtk_label_new (_("Maladies"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 48, 264);
  gtk_widget_set_size_request (label13, 64, 24);

  label12 = gtk_label_new (_("Taille"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 64, 224);
  gtk_widget_set_size_request (label12, 49, 17);

  label11 = gtk_label_new (_("Poids"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 64, 192);
  gtk_widget_set_size_request (label11, 49, 17);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed4), button11, 168, 328);
  gtk_widget_set_size_request (button11, 88, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button11), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox4), label14, FALSE, FALSE, 0);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed4), button14, 344, 328);
  gtk_widget_set_size_request (button14, 88, 32);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (button14), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox27), image29, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox27), label71, FALSE, FALSE, 0);

  label34med = gtk_label_new (_("CIN"));
  gtk_widget_show (label34med);
  gtk_fixed_put (GTK_FIXED (fixed4), label34med, 56, 16);
  gtk_widget_set_size_request (label34med, 49, 17);

  label8med = gtk_label_new (_("Nom"));
  gtk_widget_show (label8med);
  gtk_fixed_put (GTK_FIXED (fixed4), label8med, 64, 64);
  gtk_widget_set_size_request (label8med, 41, 17);

  label9med = gtk_label_new (_("Prenom"));
  gtk_widget_show (label9med);
  gtk_fixed_put (GTK_FIXED (fixed4), label9med, 56, 96);
  gtk_widget_set_size_request (label9med, 56, 24);

  label17med = gtk_label_new (_("jour"));
  gtk_widget_show (label17med);
  gtk_fixed_put (GTK_FIXED (fixed4), label17med, 112, 136);
  gtk_widget_set_size_request (label17med, 57, 24);

  label18med = gtk_label_new (_("mois"));
  gtk_widget_show (label18med);
  gtk_fixed_put (GTK_FIXED (fixed4), label18med, 232, 136);
  gtk_widget_set_size_request (label18med, 64, 25);

  label19med = gtk_label_new (_("annee"));
  gtk_widget_show (label19med);
  gtk_fixed_put (GTK_FIXED (fixed4), label19med, 344, 136);
  gtk_widget_set_size_request (label19med, 57, 25);

  label10 = gtk_label_new (_("date de\nnaissance"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed4), label10, 48, 128);
  gtk_widget_set_size_request (label10, 64, 40);

  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4med, window4med, "window4med");
  GLADE_HOOKUP_OBJECT (window4med, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4med, entry3med, "entry3med");
  GLADE_HOOKUP_OBJECT (window4med, entry4med, "entry4med");
  GLADE_HOOKUP_OBJECT (window4med, spinbutton1med, "spinbutton1med");
  GLADE_HOOKUP_OBJECT (window4med, spinbutton2med, "spinbutton2med");
  GLADE_HOOKUP_OBJECT (window4med, spinbutton3med, "spinbutton3med");
  GLADE_HOOKUP_OBJECT (window4med, entry5med, "entry5med");
  GLADE_HOOKUP_OBJECT (window4med, entry6med, "entry6med");
  GLADE_HOOKUP_OBJECT (window4med, entry7med, "entry7med");
  GLADE_HOOKUP_OBJECT (window4med, entry15med, "entry15med");
  GLADE_HOOKUP_OBJECT (window4med, label13, "label13");
  GLADE_HOOKUP_OBJECT (window4med, label12, "label12");
  GLADE_HOOKUP_OBJECT (window4med, label11, "label11");
  GLADE_HOOKUP_OBJECT (window4med, button11, "button11");
  GLADE_HOOKUP_OBJECT (window4med, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window4med, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window4med, image4, "image4");
  GLADE_HOOKUP_OBJECT (window4med, label14, "label14");
  GLADE_HOOKUP_OBJECT (window4med, button14, "button14");
  GLADE_HOOKUP_OBJECT (window4med, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window4med, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window4med, image29, "image29");
  GLADE_HOOKUP_OBJECT (window4med, label71, "label71");
  GLADE_HOOKUP_OBJECT (window4med, label34med, "label34med");
  GLADE_HOOKUP_OBJECT (window4med, label8med, "label8med");
  GLADE_HOOKUP_OBJECT (window4med, label9med, "label9med");
  GLADE_HOOKUP_OBJECT (window4med, label17med, "label17med");
  GLADE_HOOKUP_OBJECT (window4med, label18med, "label18med");
  GLADE_HOOKUP_OBJECT (window4med, label19med, "label19med");
  GLADE_HOOKUP_OBJECT (window4med, label10, "label10");

  return window4med;
}

GtkWidget*
create_window5med (void)
{
  GtkWidget *window5med;
  GtkWidget *fixed5;
  GtkWidget *entry10med;
  GtkWidget *entry11med;
  GtkObject *spinbutton4med_adj;
  GtkWidget *spinbutton4med;
  GtkObject *spinbutton5med_adj;
  GtkWidget *spinbutton5med;
  GtkObject *spinbutton6med_adj;
  GtkWidget *spinbutton6med;
  GtkWidget *entry12med;
  GtkWidget *entry13med;
  GtkWidget *entry14med;
  GtkWidget *entry16med;
  GtkWidget *label25;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *button15;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label32;
  GtkWidget *button16;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image30;
  GtkWidget *label72;
  GtkWidget *label35med;
  GtkWidget *label23med;
  GtkWidget *label24med;
  GtkWidget *label29med;
  GtkWidget *label30med;
  GtkWidget *label31med;
  GtkWidget *label26med;
  GtkWidget *label27med;
  GtkWidget *label28med;

  window5med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5med), _("window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5med), fixed5);

  entry10med = gtk_entry_new ();
  gtk_widget_show (entry10med);
  gtk_fixed_put (GTK_FIXED (fixed5), entry10med, 112, 48);
  gtk_widget_set_size_request (entry10med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10med), 8226);

  entry11med = gtk_entry_new ();
  gtk_widget_show (entry11med);
  gtk_fixed_put (GTK_FIXED (fixed5), entry11med, 112, 88);
  gtk_widget_set_size_request (entry11med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11med), 8226);

  spinbutton4med_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4med_adj), 1, 0);
  gtk_widget_show (spinbutton4med);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton4med, 160, 128);
  gtk_widget_set_size_request (spinbutton4med, 60, 27);

  spinbutton5med_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5med_adj), 1, 0);
  gtk_widget_show (spinbutton5med);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton5med, 280, 128);
  gtk_widget_set_size_request (spinbutton5med, 60, 27);

  spinbutton6med_adj = gtk_adjustment_new (1, 1900, 2013, 1, 10, 10);
  spinbutton6med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6med_adj), 1, 0);
  gtk_widget_show (spinbutton6med);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton6med, 408, 128);
  gtk_widget_set_size_request (spinbutton6med, 60, 27);

  entry12med = gtk_entry_new ();
  gtk_widget_show (entry12med);
  gtk_fixed_put (GTK_FIXED (fixed5), entry12med, 120, 176);
  gtk_widget_set_size_request (entry12med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12med), 8226);

  entry13med = gtk_entry_new ();
  gtk_widget_show (entry13med);
  gtk_fixed_put (GTK_FIXED (fixed5), entry13med, 120, 224);
  gtk_widget_set_size_request (entry13med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13med), 8226);

  entry14med = gtk_entry_new ();
  gtk_widget_show (entry14med);
  gtk_fixed_put (GTK_FIXED (fixed5), entry14med, 120, 264);
  gtk_widget_set_size_request (entry14med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14med), 8226);

  entry16med = gtk_entry_new ();
  gtk_widget_show (entry16med);
  gtk_fixed_put (GTK_FIXED (fixed5), entry16med, 112, 8);
  gtk_widget_set_size_request (entry16med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16med), 8226);

  label25 = gtk_label_new (_("date de\nnaissance"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 32, 120);
  gtk_widget_set_size_request (label25, 64, 48);

  label36 = gtk_label_new ("");
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 192, 328);
  gtk_widget_set_size_request (label36, 80, 24);

  label37 = gtk_label_new ("");
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 200, 336);
  gtk_widget_set_size_request (label37, 88, 24);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 216, 360);
  gtk_widget_set_size_request (label38, 248, 32);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed5), button15, 96, 360);
  gtk_widget_set_size_request (button15, 88, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button15), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox8), label32, FALSE, FALSE, 0);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed5), button16, 496, 360);
  gtk_widget_set_size_request (button16, 88, 32);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button16), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image30 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox28), image30, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox28), label72, FALSE, FALSE, 0);

  label35med = gtk_label_new (_("CIN"));
  gtk_widget_show (label35med);
  gtk_fixed_put (GTK_FIXED (fixed5), label35med, 40, 16);
  gtk_widget_set_size_request (label35med, 49, 17);

  label23med = gtk_label_new (_("Nom"));
  gtk_widget_show (label23med);
  gtk_fixed_put (GTK_FIXED (fixed5), label23med, 40, 48);
  gtk_widget_set_size_request (label23med, 49, 17);

  label24med = gtk_label_new (_("Prenom"));
  gtk_widget_show (label24med);
  gtk_fixed_put (GTK_FIXED (fixed5), label24med, 40, 88);
  gtk_widget_set_size_request (label24med, 56, 24);

  label29med = gtk_label_new (_("jour"));
  gtk_widget_show (label29med);
  gtk_fixed_put (GTK_FIXED (fixed5), label29med, 112, 136);
  gtk_widget_set_size_request (label29med, 32, 16);

  label30med = gtk_label_new (_("mois"));
  gtk_widget_show (label30med);
  gtk_fixed_put (GTK_FIXED (fixed5), label30med, 224, 136);
  gtk_widget_set_size_request (label30med, 49, 17);

  label31med = gtk_label_new (_("annee"));
  gtk_widget_show (label31med);
  gtk_fixed_put (GTK_FIXED (fixed5), label31med, 352, 136);
  gtk_widget_set_size_request (label31med, 49, 17);

  label26med = gtk_label_new (_("Poids"));
  gtk_widget_show (label26med);
  gtk_fixed_put (GTK_FIXED (fixed5), label26med, 40, 184);
  gtk_widget_set_size_request (label26med, 49, 17);

  label27med = gtk_label_new (_("Taille"));
  gtk_widget_show (label27med);
  gtk_fixed_put (GTK_FIXED (fixed5), label27med, 40, 232);
  gtk_widget_set_size_request (label27med, 49, 17);

  label28med = gtk_label_new (_("Maladies"));
  gtk_widget_show (label28med);
  gtk_fixed_put (GTK_FIXED (fixed5), label28med, 32, 264);
  gtk_widget_set_size_request (label28med, 64, 24);

  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5med, window5med, "window5med");
  GLADE_HOOKUP_OBJECT (window5med, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5med, entry10med, "entry10med");
  GLADE_HOOKUP_OBJECT (window5med, entry11med, "entry11med");
  GLADE_HOOKUP_OBJECT (window5med, spinbutton4med, "spinbutton4med");
  GLADE_HOOKUP_OBJECT (window5med, spinbutton5med, "spinbutton5med");
  GLADE_HOOKUP_OBJECT (window5med, spinbutton6med, "spinbutton6med");
  GLADE_HOOKUP_OBJECT (window5med, entry12med, "entry12med");
  GLADE_HOOKUP_OBJECT (window5med, entry13med, "entry13med");
  GLADE_HOOKUP_OBJECT (window5med, entry14med, "entry14med");
  GLADE_HOOKUP_OBJECT (window5med, entry16med, "entry16med");
  GLADE_HOOKUP_OBJECT (window5med, label25, "label25");
  GLADE_HOOKUP_OBJECT (window5med, label36, "label36");
  GLADE_HOOKUP_OBJECT (window5med, label37, "label37");
  GLADE_HOOKUP_OBJECT (window5med, label38, "label38");
  GLADE_HOOKUP_OBJECT (window5med, button15, "button15");
  GLADE_HOOKUP_OBJECT (window5med, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window5med, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window5med, image8, "image8");
  GLADE_HOOKUP_OBJECT (window5med, label32, "label32");
  GLADE_HOOKUP_OBJECT (window5med, button16, "button16");
  GLADE_HOOKUP_OBJECT (window5med, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window5med, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window5med, image30, "image30");
  GLADE_HOOKUP_OBJECT (window5med, label72, "label72");
  GLADE_HOOKUP_OBJECT (window5med, label35med, "label35med");
  GLADE_HOOKUP_OBJECT (window5med, label23med, "label23med");
  GLADE_HOOKUP_OBJECT (window5med, label24med, "label24med");
  GLADE_HOOKUP_OBJECT (window5med, label29med, "label29med");
  GLADE_HOOKUP_OBJECT (window5med, label30med, "label30med");
  GLADE_HOOKUP_OBJECT (window5med, label31med, "label31med");
  GLADE_HOOKUP_OBJECT (window5med, label26med, "label26med");
  GLADE_HOOKUP_OBJECT (window5med, label27med, "label27med");
  GLADE_HOOKUP_OBJECT (window5med, label28med, "label28med");

  return window5med;
}

GtkWidget*
create_window6med (void)
{
  GtkWidget *window6med;
  GtkWidget *fixed6;
  GtkObject *spinbutton7med_adj;
  GtkWidget *spinbutton7med;
  GtkObject *spinbutton8med_adj;
  GtkWidget *spinbutton8med;
  GtkObject *spinbutton9med_adj;
  GtkWidget *spinbutton9med;
  GtkWidget *entry17med;
  GtkWidget *entry18med;
  GtkWidget *entry19med;
  GtkWidget *button18;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label48;
  GtkWidget *button21;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image31;
  GtkWidget *label73;
  GtkWidget *label54med;
  GtkWidget *label53med;
  GtkWidget *label52med;
  GtkWidget *label47med;
  GtkWidget *label46med;
  GtkWidget *label51med;
  GtkWidget *label45;

  window6med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6med), _("window6"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6med), fixed6);

  spinbutton7med_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton7med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7med_adj), 1, 0);
  gtk_widget_show (spinbutton7med);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton7med, 128, 16);
  gtk_widget_set_size_request (spinbutton7med, 60, 27);

  spinbutton8med_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8med_adj), 1, 0);
  gtk_widget_show (spinbutton8med);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton8med, 264, 16);
  gtk_widget_set_size_request (spinbutton8med, 60, 27);

  spinbutton9med_adj = gtk_adjustment_new (1900, 1900, 2013, 1, 10, 10);
  spinbutton9med = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9med_adj), 1, 0);
  gtk_widget_show (spinbutton9med);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton9med, 400, 16);
  gtk_widget_set_size_request (spinbutton9med, 60, 27);

  entry17med = gtk_entry_new ();
  gtk_widget_show (entry17med);
  gtk_fixed_put (GTK_FIXED (fixed6), entry17med, 72, 104);
  gtk_widget_set_size_request (entry17med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17med), 8226);

  entry18med = gtk_entry_new ();
  gtk_widget_show (entry18med);
  gtk_fixed_put (GTK_FIXED (fixed6), entry18med, 72, 152);
  gtk_widget_set_size_request (entry18med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18med), 8226);

  entry19med = gtk_entry_new ();
  gtk_widget_show (entry19med);
  gtk_fixed_put (GTK_FIXED (fixed6), entry19med, 72, 64);
  gtk_widget_set_size_request (entry19med, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19med), 8226);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed6), button18, 112, 200);
  gtk_widget_set_size_request (button18, 96, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button18), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox16), label48, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed6), button21, 272, 200);
  gtk_widget_set_size_request (button21, 96, 32);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (button21), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image31 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox29), image31, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox29), label73, FALSE, FALSE, 0);

  label54med = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label54med);
  gtk_fixed_put (GTK_FIXED (fixed6), label54med, 344, 24);
  gtk_widget_set_size_request (label54med, 49, 17);

  label53med = gtk_label_new (_("Mois"));
  gtk_widget_show (label53med);
  gtk_fixed_put (GTK_FIXED (fixed6), label53med, 208, 24);
  gtk_widget_set_size_request (label53med, 49, 17);

  label52med = gtk_label_new (_("Jour"));
  gtk_widget_show (label52med);
  gtk_fixed_put (GTK_FIXED (fixed6), label52med, 64, 24);
  gtk_widget_set_size_request (label52med, 49, 17);

  label47med = gtk_label_new (_("Dur\303\251e"));
  gtk_widget_show (label47med);
  gtk_fixed_put (GTK_FIXED (fixed6), label47med, 8, 160);
  gtk_widget_set_size_request (label47med, 49, 17);

  label46med = gtk_label_new (_("Horaire"));
  gtk_widget_show (label46med);
  gtk_fixed_put (GTK_FIXED (fixed6), label46med, 8, 104);
  gtk_widget_set_size_request (label46med, 56, 24);

  label51med = gtk_label_new (_("CIN"));
  gtk_widget_show (label51med);
  gtk_fixed_put (GTK_FIXED (fixed6), label51med, 8, 72);
  gtk_widget_set_size_request (label51med, 49, 17);

  label45 = gtk_label_new (_("Date"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed6), label45, 0, 24);
  gtk_widget_set_size_request (label45, 49, 17);

  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6med, window6med, "window6med");
  GLADE_HOOKUP_OBJECT (window6med, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6med, spinbutton7med, "spinbutton7med");
  GLADE_HOOKUP_OBJECT (window6med, spinbutton8med, "spinbutton8med");
  GLADE_HOOKUP_OBJECT (window6med, spinbutton9med, "spinbutton9med");
  GLADE_HOOKUP_OBJECT (window6med, entry17med, "entry17med");
  GLADE_HOOKUP_OBJECT (window6med, entry18med, "entry18med");
  GLADE_HOOKUP_OBJECT (window6med, entry19med, "entry19med");
  GLADE_HOOKUP_OBJECT (window6med, button18, "button18");
  GLADE_HOOKUP_OBJECT (window6med, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window6med, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window6med, image16, "image16");
  GLADE_HOOKUP_OBJECT (window6med, label48, "label48");
  GLADE_HOOKUP_OBJECT (window6med, button21, "button21");
  GLADE_HOOKUP_OBJECT (window6med, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window6med, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window6med, image31, "image31");
  GLADE_HOOKUP_OBJECT (window6med, label73, "label73");
  GLADE_HOOKUP_OBJECT (window6med, label54med, "label54med");
  GLADE_HOOKUP_OBJECT (window6med, label53med, "label53med");
  GLADE_HOOKUP_OBJECT (window6med, label52med, "label52med");
  GLADE_HOOKUP_OBJECT (window6med, label47med, "label47med");
  GLADE_HOOKUP_OBJECT (window6med, label46med, "label46med");
  GLADE_HOOKUP_OBJECT (window6med, label51med, "label51med");
  GLADE_HOOKUP_OBJECT (window6med, label45, "label45");

  return window6med;
}

GtkWidget*
create_window7med (void)
{
  GtkWidget *window7med;
  GtkWidget *fixed7;
  GtkWidget *treeview2med;
  GtkWidget *entry21med;
  GtkWidget *button23;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label58;
  GtkWidget *button25;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label60;
  GtkWidget *button22;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image32;
  GtkWidget *label74;
  GtkWidget *label57med;

  window7med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7med), _("window7"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7med), fixed7);

  treeview2med = gtk_tree_view_new ();
  gtk_widget_show (treeview2med);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview2med, 32, 40);
  gtk_widget_set_size_request (treeview2med, 328, 272);

  entry21med = gtk_entry_new ();
  gtk_widget_show (entry21med);
  gtk_fixed_put (GTK_FIXED (fixed7), entry21med, 440, 392);
  gtk_widget_set_size_request (entry21med, 72, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21med), 8226);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed7), button23, 216, 336);
  gtk_widget_set_size_request (button23, 96, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button23), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox20), label58, FALSE, FALSE, 0);

  button25 = gtk_button_new ();
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed7), button25, 392, 328);
  gtk_widget_set_size_request (button25, 104, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button25), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox22), label60, FALSE, FALSE, 0);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed7), button22, 552, 0);
  gtk_widget_set_size_request (button22, 74, 29);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (button22), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image32 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox30), image32, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox30), label74, FALSE, FALSE, 0);

  label57med = gtk_label_new (_("CIN"));
  gtk_widget_show (label57med);
  gtk_fixed_put (GTK_FIXED (fixed7), label57med, 392, 392);
  gtk_widget_set_size_request (label57med, 49, 17);

  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_button23_clicked),
                    NULL);
  g_signal_connect ((gpointer) button25, "clicked",
                    G_CALLBACK (on_button25_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_button22_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7med, window7med, "window7med");
  GLADE_HOOKUP_OBJECT (window7med, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7med, treeview2med, "treeview2med");
  GLADE_HOOKUP_OBJECT (window7med, entry21med, "entry21med");
  GLADE_HOOKUP_OBJECT (window7med, button23, "button23");
  GLADE_HOOKUP_OBJECT (window7med, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window7med, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window7med, image20, "image20");
  GLADE_HOOKUP_OBJECT (window7med, label58, "label58");
  GLADE_HOOKUP_OBJECT (window7med, button25, "button25");
  GLADE_HOOKUP_OBJECT (window7med, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window7med, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window7med, image22, "image22");
  GLADE_HOOKUP_OBJECT (window7med, label60, "label60");
  GLADE_HOOKUP_OBJECT (window7med, button22, "button22");
  GLADE_HOOKUP_OBJECT (window7med, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window7med, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window7med, image32, "image32");
  GLADE_HOOKUP_OBJECT (window7med, label74, "label74");
  GLADE_HOOKUP_OBJECT (window7med, label57med, "label57med");

  return window7med;
}

GtkWidget*
create_window8med (void)
{
  GtkWidget *window8med;
  GtkWidget *fixed8;
  GtkWidget *entry22med;
  GtkWidget *entry23med;
  GtkWidget *entry24med;
  GtkWidget *entry25med;
  GtkWidget *entry26med;
  GtkWidget *button27;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image34;
  GtkWidget *label75;
  GtkWidget *label67;
  GtkWidget *image27;
  GtkWidget *label63med;
  GtkWidget *label64med;
  GtkWidget *label65med;
  GtkWidget *label66med;
  GtkWidget *label68med;

  window8med = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8med), _("window8"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8med), fixed8);

  entry22med = gtk_entry_new ();
  gtk_widget_show (entry22med);
  gtk_fixed_put (GTK_FIXED (fixed8), entry22med, 448, 64);
  gtk_widget_set_size_request (entry22med, 184, 32);
  gtk_editable_set_editable (GTK_EDITABLE (entry22med), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry22med), _("Mezri"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22med), 8226);

  entry23med = gtk_entry_new ();
  gtk_widget_show (entry23med);
  gtk_fixed_put (GTK_FIXED (fixed8), entry23med, 448, 112);
  gtk_widget_set_size_request (entry23med, 184, 32);
  gtk_editable_set_editable (GTK_EDITABLE (entry23med), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry23med), _("chaima"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23med), 8226);

  entry24med = gtk_entry_new ();
  gtk_widget_show (entry24med);
  gtk_fixed_put (GTK_FIXED (fixed8), entry24med, 448, 160);
  gtk_widget_set_size_request (entry24med, 184, 32);
  gtk_editable_set_editable (GTK_EDITABLE (entry24med), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry24med), _("95420746"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24med), 8226);

  entry25med = gtk_entry_new ();
  gtk_widget_show (entry25med);
  gtk_fixed_put (GTK_FIXED (fixed8), entry25med, 448, 208);
  gtk_widget_set_size_request (entry25med, 184, 32);
  gtk_editable_set_editable (GTK_EDITABLE (entry25med), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry25med), _("chaima.mezri@gmail.com"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25med), 8226);

  entry26med = gtk_entry_new ();
  gtk_widget_show (entry26med);
  gtk_fixed_put (GTK_FIXED (fixed8), entry26med, 448, 256);
  gtk_widget_set_size_request (entry26med, 184, 32);
  gtk_editable_set_editable (GTK_EDITABLE (entry26med), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry26med), _("09927672"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26med), 8226);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed8), button27, 448, 344);
  gtk_widget_set_size_request (button27, 96, 32);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button27), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image34 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox31), image34, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox31), label75, FALSE, FALSE, 0);

  label67 = gtk_label_new (_("MY GYM"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed8), label67, 320, 8);
  gtk_widget_set_size_request (label67, 80, 24);

  image27 = create_pixmap (window8med, "cahyma3.png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed8), image27, 0, 32);
  gtk_widget_set_size_request (image27, 360, 340);

  label63med = gtk_label_new (_("Nom"));
  gtk_widget_show (label63med);
  gtk_fixed_put (GTK_FIXED (fixed8), label63med, 376, 72);
  gtk_widget_set_size_request (label63med, 49, 17);

  label64med = gtk_label_new (_("Prenom"));
  gtk_widget_show (label64med);
  gtk_fixed_put (GTK_FIXED (fixed8), label64med, 368, 112);
  gtk_widget_set_size_request (label64med, 56, 24);

  label65med = gtk_label_new (_("Telephone"));
  gtk_widget_show (label65med);
  gtk_fixed_put (GTK_FIXED (fixed8), label65med, 352, 160);
  gtk_widget_set_size_request (label65med, 72, 24);

  label66med = gtk_label_new (_("E-mail"));
  gtk_widget_show (label66med);
  gtk_fixed_put (GTK_FIXED (fixed8), label66med, 376, 216);
  gtk_widget_set_size_request (label66med, 49, 17);

  label68med = gtk_label_new (_("CIN"));
  gtk_widget_show (label68med);
  gtk_fixed_put (GTK_FIXED (fixed8), label68med, 384, 264);
  gtk_widget_set_size_request (label68med, 49, 17);

  g_signal_connect ((gpointer) button27, "clicked",
                    G_CALLBACK (on_button27_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8med, window8med, "window8med");
  GLADE_HOOKUP_OBJECT (window8med, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8med, entry22med, "entry22med");
  GLADE_HOOKUP_OBJECT (window8med, entry23med, "entry23med");
  GLADE_HOOKUP_OBJECT (window8med, entry24med, "entry24med");
  GLADE_HOOKUP_OBJECT (window8med, entry25med, "entry25med");
  GLADE_HOOKUP_OBJECT (window8med, entry26med, "entry26med");
  GLADE_HOOKUP_OBJECT (window8med, button27, "button27");
  GLADE_HOOKUP_OBJECT (window8med, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window8med, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (window8med, image34, "image34");
  GLADE_HOOKUP_OBJECT (window8med, label75, "label75");
  GLADE_HOOKUP_OBJECT (window8med, label67, "label67");
  GLADE_HOOKUP_OBJECT (window8med, image27, "image27");
  GLADE_HOOKUP_OBJECT (window8med, label63med, "label63med");
  GLADE_HOOKUP_OBJECT (window8med, label64med, "label64med");
  GLADE_HOOKUP_OBJECT (window8med, label65med, "label65med");
  GLADE_HOOKUP_OBJECT (window8med, label66med, "label66med");
  GLADE_HOOKUP_OBJECT (window8med, label68med, "label68med");

  return window8med;
}

